### ISSUE TITLE
Определение параметров функций

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#2]
Сейчас определение параметров завязано на наличие "Знач".
Необходимо реализовать определение любых параметров.
![default](https://cloud.githubusercontent.com/assets/1132840/11536733/d803527c-992a-11e5-8578-35206e1fb672.PNG)

**Comment by nixel2007** [comment]
@vsuh можешь что-нибудь посоветовать по этому пункту? С регулярками и TextMate только недавно начал работать.

**Comment by bambr1975** [comment]
Вставь в самое начало - должно помочь и для https://github.com/xDrivenDevelopment/1c-syntax/issues/1
```
patterns:
- name: variable.complex.ssraw
  begin: '(?i:(процедура|функция) ([a-zа-я0-9_]+)\s*\()'
  beginCaptures:
    '1': {name: storage.type.1с}
    '2': {name: entity.name.function.1с}
  end: \)
  patterns:
  - name: comment.line.double-slash.1с
    match: (//.*\n)
  - name: storage.modifier.1с
    match: (?i:Знач)
  - name: variable.parameter.1с
    match: (?i:[a-zа-я0-9_]+)
```

**Comment by nixel2007** [comment]
Идентификатор ssraw - это с примера осталось? Должно быть `1c`?
Зачем во вложенном паттерне `comment.line.double-slash`? Разве он не определится, если будет выше по тексту файла? 

Спасибо, попробую!

**Comment by bambr1975** [comment]
да, ты прав, comment.line.double-slash можно убрать, если определить его выше по тексту. А name, там кстати, вообще не нужен - можно первой строкой поставить ```begin: '(?i:(процедура|функция) ([a-zа-я0-9_]+)\s*\()'```

**Comment by artbear** [comment]
После процедура|функция не хватает \s*

пт, 4 Дек 2015, 10:02, bambr1975 <notifications@github.com>:

**Comment by artbear** [comment]
Точнее,\s+

пт, 4 Дек 2015, 10:04, Артур Аюханов <aartbear@gmail.com>:

**Comment by nixel2007** [comment]
```
- comment: "Proc and function defenition"
  begin: '(?i:(Процедура|Функция)\s+([a-zа-я0-9_]+)\s*\()\s*(Экспорт)?'
  beginCaptures:
    '1': {name: storage.type.1с}
    '2': {name: entity.name.function.1с}
  end: \)
  patterns:
  - include: $self
  - name: storage.modifier.1с
    match: (?i:\b(Знач|Экспорт)\b)
  - name: variable.parameter.1с
    match: (?i:[a-zа-я0-9_]+)
```

Поправил замечания, добавил определение Экспорт, добавил include для работы всех остальных регулярок (операторы, даты, строки и т.д.)

В текущей реализации осталось только вот такая ситуация:
![default](https://cloud.githubusercontent.com/assets/1132840/11584233/487a7f8c-9a73-11e5-8870-bc1951a71f0c.PNG)
ЧтоТоЕще не парсится как какой-то из типов и попадает в класс `variable.parameter`.
Но вроде это в любом случае невалидный код, а примитивные типы под парс попадают.
