### ISSUE TITLE
[GitHub] Подсветка синтаксиса

### ISSUE THREAD

**Issue by nixel2007** [xDrivenDevelopment/1c-syntax#29]
На досуге просматривал формат подвестки синтаксиса, который использует github.
В его основе лежит сторонняя библиотека, которая импортирует tmBundle с грамматикой.

Как поразительно соблазительную и даже относительно реальную можно поставить цель добавить поддержку синтаксиса 1С в сам GitHub. Мне кажется это будет оооочень круто.

Не совсем, правда, понятно, как к этому может отнестись сама 1С.

**Comment by artbear** [comment]
Хорошая и нужная тема.
Не думаю, что 1с будет против,не вижу коммерческой выгоды или торговых
знаков

чт, 10 Дек 2015, 15:31, Nikita Gryzlov <notifications@github.com>:

**Comment by allustin** [comment]
Эта тема обсуждалась на партнерке с Петром Грибановым. 

Ни до чего конкретного не договорились, но предварительно негатива такое предложение не вызвало, а скорее даже наоборот заинтересовало. 

Я также изучал этот вопрос - его нужно разделить на 2 этапа

* перейти на bsl, mdo и подобные расширения и добавить их в Лингвиста https://github.com/github/linguist

* ну и как ты правильно заметил - https://github.com/github/linguist/tree/master/vendor/grammars - добавить сюда грамматику языка

в своё время в наши версии precommit и unpack даже была добавлена возможность переименования модулей из txt в bsl

**Comment by nixel2007** [comment]
Отлично, значит, это действительно реально сделать.

1) Разве 1сный код может быть где-то кроме bsl? mdo - формат описания метаданных, это XML, и 1С (BSL) тут вроде не причем.
2) Судя по второй ссылке можно использовать текущий готовый пакет от Sublime Text (после закрытия issue, касающихся грамматики, обязательно #6 и желательно #25).

**Comment by allustin** [comment]
@nixel2007 с MDO объектами сложный момент - фактически да, это XML, но тогда Лингвист покажет статистику репозитория как XML <N процентов>, а по красивому это не правильно.

Должна быть красивая картинка - 1C Код + 24%, 1С Метаданные + 60% Other 16%. По крайней мере при обсуждении с авторами Cucumber родилось именно такое мнение

то есть для нашего формата bootstrap мы хотели поддержку нескольких языков

Cucumber - https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L696
Yaml - https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L696 (или JSON)

а 1C мы предлагали объединить в группу https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L696

фактически ожидаемый конечный результат это - чтобы на 1С git репозитории мы имели статистику

* cucumber - чтобы понимать, проект качественный или нет
* yaml - чтобы понимать можно ли собрать проект за 1С шаг
* 1C - чтобы было понято что тут есть 1С-ный код
* 1C Metadata - чтобы было понятно, что это не просто внешняя обработка, а целая конфигурация 1С

P.S. Кстати для @EvilBeaver то же бы надо было подать регистрацию расширения .os

**Comment by nixel2007** [comment]
@allustin со ссылками на строки что-то не так, можешь отредактировать, чтобы правильно понять твою мысль? :)

**Comment by allustin** [comment]
@nixel2007 - у меня открывается во всех трех браузерах. Прокомментирую по другому

нас интересует следующие вещи в Лингвисте

* Имя для отображения статистики
* Группа расширений
* Тип подсветки

и фактически нам нужно добавить 2 конструкции

определения самого языка

```
1S Enterprise Lang:
  type: programming
  color: "#814CCC"
  group: 1S Enterprise
  extensions:
  - .bsl
  tm_scope: 1c-syntax.xml
```

и определение метаданных для уровня фреймворка

```
1S Enterprise Metadata:
  type: data
  color: "#814C05"
  group: 1S Enterprise
  extensions:
  - .mdo
  tm_scope: text.xml
  ace_mode: xml
```

Это то что мы накопали перед партнеркой и пока остановили это дело - пока не стабильизируется формат хранения (а то к марту опять обещают изменения)

То есть - я имею ввиду, что можно все файлы сгруппировать в одну группу 1S Enterprise, а подсветку можно делать по разному. У меня Андрей (спец по С++) в ноябре даже смотрел можно ли сделать так, чтобы Лингвист 1С метаданные подсвечивал как-то в виде графики ;-)

**Comment by nixel2007** [comment]
> у меня открывается во всех трех браузерах. Прокомментирую по другому

я увидел ссылки на конкретные номера строк. Подумал, что ты на них акцентируешь внимание.

> и фактически нам нужно добавить 2 конструкции

Я правильно понимаю, что это можно сделать хоть сейчас?  
Только, на мой взгляд, надо подкорректировать на такое:

```
1C Enterprise Lang:
  type: programming
  color: "#814CCC"
  group: 1C Enterprise
  extensions:
  - .bsl
  - .os
  tm_scope: source.bsl

1C Enterprise Metadata:
  type: data
  color: "#814C05"
  group: 1C Enterprise
  extensions:
  - .mdo
  tm_scope: text.xml
  ace_mode: xml
```

(расширения, scope, и сменил 1S - 1C)
